(function ($)
{
    // attach an event handler to the entire window
    $(window).on('load', function () // run an anonymous function when the window is fully loaded
    {
        // call flexslider plugin (contained at 'plugins/jquery.flexslider-min.js') on the element with the id 'testimonial-slider'
        $('#testimonial-slider').flexslider( // flexslider takes predefined properties and values
        {
            namespace: 'flex-', // prefix string attached to the class of every element generated by the plugin
            controlsContainer: '', // declare which container the navigation elements should be appended to, property is ignored if given element is not found
            animation: 'fade', // animation type, options are 'fade' or 'slide'
            controlNav: true, // boolean property to create navigation for paging control of each slide
            directionNav: false, // boolean property to create navigation for next/previous navigation
            smoothHeight: false, // boolean property to allow height of the slider to animate smoothly in horizontal mode, will take up more browser memory if set to 'true'
            slideshowSpeed: 4000, // set the speed of the slideshow cycling, in milliseconds; 4000ms = 4s; new slide appears after 4 seconds
            animationSpeed: 500, // set the speed of animations, in milliseconds; 500ms = 0.5s; animation takes 1/2 second
            randomize: false, // boolean property to randomize slide order, each slide is contained in a <div> element and one slide appears consecutively after the previous slide
            touch: true // boolean property to allow touch swipe navigation of the slider on touch-enabled devices, will work on most smartphones/tablets
        });
    });
})(jQuery); // call this function under jQuery namespace